
ALTER TABLE cohort DROP COLUMN IF EXISTS "created_at";
ALTER TABLE cohort ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMPTZ DEFAULT now();
ALTER TABLE cohort DROP COLUMN IF EXISTS "updated_at";
ALTER TABLE cohort ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMPTZ DEFAULT now();

ALTER TABLE plan DROP COLUMN IF EXISTS "created_at";
ALTER TABLE plan ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMPTZ DEFAULT now();
ALTER TABLE plan DROP COLUMN IF EXISTS "updated_at";
ALTER TABLE plan ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMPTZ DEFAULT now();

ALTER TABLE student DROP COLUMN IF EXISTS "created_at";
ALTER TABLE student ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMPTZ DEFAULT now();
ALTER TABLE student DROP COLUMN IF EXISTS "updated_at";
ALTER TABLE student ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMPTZ DEFAULT now();
