ALTER TABLE cohort DROP COLUMN id CASCADE;
ALTER TABLE cohort ADD COLUMN id UUID PRIMARY KEY;
ALTER TABLE enrollment ALTER COLUMN cohort_id TYPE UUID USING id::UUID;
ALTER TABLE plan ALTER COLUMN cohort_id TYPE UUID USING id::UUID;