ALTER TABLE student ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE student ADD COLUMN IF NOT EXISTS time_zone TEXT;
ALTER TABLE timewindow ADD COLUMN IF NOT EXISTS start_date_time TIMESTAMP;
ALTER TABLE timewindow ADD COLUMN IF NOT EXISTS end_date_time TIMESTAMP;